### ISSUE TITLE
Import each file into R

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment-CCLE#1]
Step 1 is to import each file into R, and store each assay as the simplest possible basic objects (matrix, data.frame, DataFrame, if possible) in .rds files. Not sure offhand about the .maf file.  From Phil's email:

For the CCLE MAEO I would suggest using the following datasets available from http://www.broadinstitute.org/ccle/data/browseData:

CCLE Affymetrix data - CCLE_Expression_Entrez_2012-09-29.gct
CCLE copy number data - CCLE_copynumber_byGene_2012-09-29.txt
CCLE hybrid capture sequencing data - CCLE_hybrid_capture1650_hg19_NoCommonSNPs_NoNeutralVariants_CDS_2012.05.07.maf
CCLE compound screening data - CCLE_NP24.2009_Drug_data_2012.02.20.csv

**Comment by schifferl** [comment]
Ok, I am on it 👍

**Comment by schifferl** [comment]
Issue is closed by 5039567, however I have not included the data as CCLE does not include terms of access. Their site https://www.broadinstitute.org/ccle/toa/termsOfAccess/1713/ appears to be blank.

**Comment by LiNk-NY** [comment]
Yeah, we don't want to include the data here because it's too big and it shouldn't be published.
