### ISSUE TITLE
multiple cell line rownames in pData

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MultiAssayExperiment-CCLE#3]
@lwaldron @chapmandu2 @schifferl 
The structure for the `pData` involves multiple lines for each cell line. We want to reduce it so that there is one row per cell line name inside a `DataFrame`. The issue were facing here is that we're not sure how to include all of it in one line. 

```
library(readr); library(S4Vectors)
pData <- read_csv("rawdata/CCLE_NP24.2009_Drug_data_2012.02.20.csv")
pData <- DataFrame(pData)
splitData <- split(pData, pData$CCLE.Cell.Line.Name)
splitData[[1]]
```

**Comment by chapmandu2** [comment]
I must admit I'm not entirely comfortable with this approach but see why you want to keep it to one row per cell line.  Already in the CCLE data the individual points on the dose response curve are reduced to a string.  Do you think that accomodating tall/skinny data is something that MAE should just do?

You could also represent it as a matrix or series of matrices.  So cell lines by row and compounds by column, then EC50 (say) as the value.  But then you'd need multiple matrices to be able to cope with the different metrics - IC50, ActArea etc.  Perhaps this is more natural than the data frame of data frames approach?

**Comment by lwaldron** [comment]
Where is the file `rawdata/CCLE_NP24.2009_Drug_data_2012.02.20.csv`? I'd like to take a look.

**Comment by lwaldron** [comment]
But briefly, this idea is this:

```
library(S4Vectors)
df = DataFrame(a=SimpleList(1:2, 1:3, 1:4),
               b=SimpleList(1:10, 1:2, 1:5))
```

which should allow arbitrary data stored for each cell line on its row of the pData.

**Comment by LiNk-NY** [comment]
@chapmandu2 @lwaldron @schifferl 
Sorry, all the `rawdata` files are not included by default. 
Thank you Professor Waldron.
This solution escaped me when I posted this. We ultimately want a 504 cell lines by 13 variables `DataFrame`.
I have an _preliminary_ implementation of this for your testing. Let me know what you think. 

```
splitData <- split(pData, pData$CCLE.Cell.Line.Name)
gg <- lapply(splitData, function(aa) {
DataFrame(lapply(aa, function(column) {
    if (length(unique(column)) == 1L) {
        return(unique(column))
    } else {
        return(SimpleList(column))
    }
}))
})
cc <- do.call(rbind, gg)
rownames(cc) <- cc$CCLE.Cell.Line.Name
cc <- cc[, -1]
cc
```

**Comment by lwaldron** [comment]
I've been getting a "Service Temporarily Unavailable" message from broadinstitute.org/ccle for the past couple days so I can't check. Perhaps you could attach the CCLE_NP24.2009_Drug_data_2012.02.20.csv file here?  Pretty sure they won't mind. The above code seems a little complicated, but if it results in columns of pData that are numeric/character when there is only one value per cell line, and SimpleList when there are multiple values per cell line, then that's what I had in mind.  Alternatively you could post the resulting cc object, but I think we're on the same page.

**Comment by lwaldron** [comment]
Finally logged in: [Drug data](https://github.com/waldronlab/MultiAssayExperiment-CCLE/files/266344/CCLE_NP24.2009_Drug_data_2015.02.24.csv.zip)

**Comment by lwaldron** [comment]
1. add names to list elements
2. make a nested list, so that e.g.:

```
> as.list(cc$Doses..uM.[[5]])
[[1]]
 [1] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
 [3] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
 [5] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
 [7] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
 [9] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
[11] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
[13] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
[15] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
[17] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
[19] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
[21] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0025,.0080,.025,.080,.25,.80,2.53,8"
[23] ".0025,.0080,.025,.080,.25,.80,2.53,8" ".0080,.025,.080,.25,.80,2.53,8"   
```

is instead a named SimpleList of length 24, with numeric vectors in each element.
