### ISSUE TITLE
Provide an esetToPhyloseq conversion function

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment-CCLE#7]
Can base it on the metaphlanToPhyloseq function at: https://github.com/waldronlab/EPIC2016

This seems easier at this point than converting the datasets to phyloseq.

**Comment by schifferl** [comment]
I will work on the function now but just thinking maybe it should go in the curatedMetaGenomic package instead. Either way, will get it done ASAP and contribute the code.

**Comment by lwaldron** [comment]
This is in the wrong GitHub repo, belongs in vobencha/curatedMetagenomicData :)
