### ISSUE TITLE
advice on source data retrieval out of date

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment-CCLE#9]
http://www.broadinstitute.org/ccle/data/browseData

has changed to 

https://portals.broadinstitute.org/ccle/data ... the data mentioned in the advice comments can be retrieved by wget, it seems, but the URLs have to be correct, e.g.

https://data.broadinstitute.org/ccle_legacy_data/hybrid_capture_sequencing/CCLE_hybrid_capture1650_hg19_allVariants_2012.05.07.maf.gz

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 
It looks like the files we were using are no longer being kept in the `ccle_legacy_data`. 
We would have to use the newer versions of the files. 

I will add the new names in a future commit. Thanks. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Fixed in e69a305c0126ac962045643846c7a71653439715
